# 屏幕监控配置
monitor:
  # 监控开关键，按一次开启，再按一次关闭
  # 支持的按键详见下文
  toggle_key: "f12"

  # OCR 识别区域
  # 单位：屏幕像素
  # 程序会截图这个矩形区域识别“已加入人数/人数上限”
  # x, y: 矩形左上角坐标
  # width, height: 矩形宽高
  #
  # 全屏游戏时各屏幕分辨率推荐设置：
  # 4k (3840x2160): x=3609, y=1974, width=172, height=55
  # 2k (2560x1440): x=2409, y=1314, width=105, height=37
  # 1080p (1920x1080): x=1807, y=986, width=78, height=27
  region:
    x: 3609
    y: 1974
    width: 172
    height: 55

# 执行动作
actions:
  # 动作序列
  # key: 按下的键。支持 'm', 'enter', 'up', 'down' 等（还支持很多其它的，但是卡CEO时用不到）
  # hold: 按下持续时长(秒)。默认0.1秒
  # delay: 每次按键后的延迟(秒)。默认0.05秒
  # times: 按键次数。默认1次
  sequence:
    - key: "m" # 打开菜单
      hold: 0.03
      delay: 0.18
    - key: "down" # 向下选择两次
      hold: 0.03
      delay: 0.06
      times: 2
    - key: "enter" # 连续确认三次
      hold: 0.03
      delay: 0.06
      times: 3
